### ISSUE TITLE
getOrThrow wraps exception in RuntimeException

### ISSUE THREAD

**Issue by torgeirsh** [jrudolph/json-lenses#21]
The implementation of getOrThrow wraps the Throwable in Left inside a RuntimeException. Wouldn't it be more convenient to throw the Throwable directly? That way one could simply catch DeserializationError instead of catching RuntimeException and check if it contains a DeserializationError.

**Comment by jrudolph** [comment]
@torgeirsh I understand what you are saying. The problem is that you will then lose the stack trace of the function that called `getOrThrow` in the first place which means that you may catch an exception which doesn't even contain the frame which catched the exception. This leads to very confusing stack traces that are sometimes impossible to debug later on. So, this is by design.

`getOrThrow` is more of a last resort solution anyway. Usually, you would use pattern matching or the combinators to deal with `Either` and only handle errors on the top level (or wherever you would have put the exception handler).

**Comment by torgeirsh** [comment]
Ah I see, that makes sense. I'll investigate the Either variants, thanks!
