### ISSUE TITLE
Access multiple fields

### ISSUE THREAD

**Issue by torgeirsh** [jrudolph/json-lenses#22]
It would be nice to access multiple fields like this:

    ("a", "b", "c").tryGet[(A, B, C)](json)

The current way, unless I'm missing something, has a lot of repetition:

    for {
        a <- "a".tryGet[A](json)
        b <- "b".tryGet[B](json)
        c <- "c".tryGet[C](json)
    } yield (a, b, c)

**Comment by jrudolph** [comment]
The reason, that this is currently not possible is that a lens can only extract a `JsValue` (this is everywhere hardcoded in the types). What would be needed to support your case would be extracting a tuple which currently is not possible. What you can do instead, especially if you are only interested in three fields named `a`, `b`, and `c`, is defining a case class `ABC` that receives `a`, `b`, and `c`, then define a `JsonFormat[ABC]` and with the format in scope, use `extract[ABC]` instead of `tryGet` to receive the values together.

Does that make sense?

**Comment by torgeirsh** [comment]
Yes, that makes sense. Thanks! `tryGet[ABC]` seems to work as well, by the way.
